build_and_push_images:
  runs-on: ubuntu-latest
  needs: test_and_lint_backends

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Validate AZURE_CREDENTIALS JSON (quick sanity check)
    - name: Validate AZURE_CREDENTIALS JSON
      run: |
        echo '${{ secrets.AZURE_CREDENTIALS }}' > creds.json
        python - <<'PY'
        import json
        j=json.load(open('creds.json'))
        for k in ['clientId','clientSecret','tenantId','subscriptionId']:
            assert k in j and j[k], f"Missing or empty: {k}"
        print("AZURE_CREDENTIALS JSON looks OK")
        PY

    # Azure login using your Service Principal JSON
    - name: Azure Login (SDK-auth JSON)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Verify Azure login
      run: az account show

    # Login to ACR - use registry NAME, not domain
    - name: Login to Azure Container Registry
      run: |
        REG_NAME="${{ secrets.AZURE_CONTAINER_REGISTRY }}"; REG_NAME="${REG_NAME%%.*}"  # strip ".azurecr.io"
        az acr login --name "$REG_NAME"
        az acr show --name "$REG_NAME" --query loginServer

    # Build & push images with unique tag
    - name: Build and Push Product Service Image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/product_service:${{ github.sha }}-${{ github.run_id }} ./backend/product_service
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/product_service:${{ github.sha }}-${{ github.run_id }}

    - name: Build and Push Order Service Image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/order_service:${{ github.sha }}-${{ github.run_id }} ./backend/order_service
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/order_service:${{ github.sha }}-${{ github.run_id }}

    # Safe logout (won’t fail if login didn’t happen)
    - name: Logout from Azure
      if: always()
      run: az account show >/dev/null 2>&1 && az logout || echo "No active az session to logout."
