name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  # Secrets you must set in the repo:
  #   AZURE_CREDENTIALS .......... full SP JSON
  #   AZURE_CONTAINER_REGISTRY ... e.g. sit722acr19861.azurecr.io
  #   AZURE_ACR_NAME ............. e.g. sit722acr19861
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # IMPORTANT: use registry *name* here (no .azurecr.io)
      - name: Login to Azure Container Registry
        run: az acr login --name "${{ secrets.AZURE_ACR_NAME }}"

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout from Azure
        if: always()
        run: az logout
